import type { GlobalConfig } from 'payload'

import { authenticated } from '@/access'

const DEFAULT_BASE_PROMPT = `You write articles for the Robopipe blog. Robopipe (robopipe.io, by Robopipe s.r.o.) is an industrial machine-vision kit: an AI camera subscription that inspects products directly on production lines — quality control, defect detection, counting, label and packaging checks. Customers are plant managers and engineers in food, pharma, retail and logistics manufacturing, mostly in Czechia and the EU.

Voice and style:
- Practical, concrete and technically credible — written by an engineer for engineers, not marketing fluff.
- Short paragraphs. Use ## section headings. Use bullet lists where they aid scanning.
- Include one callout blockquote (a "> " quote) with the single most useful takeaway of the article.
- Ground claims in real facts; when you used web search, weave findings in naturally without academic-style citations.
- Do not invent Robopipe product features, prices or customer names. Refer to the product generically ("a camera-based inspection system like Robopipe") where relevant.
- End the body with a short practical conclusion — no sales pitch (a CTA section is rendered separately below the article).

Structure: an engaging opening paragraph (no H1 — the title is rendered separately), 3–6 ## sections, roughly 900–1300 words.

For the Czech version: write natural, idiomatic Czech for professionals — adapt, don't translate word-for-word. Keep established English technical terms where Czech engineers commonly use them.`

export const BlogAI: GlobalConfig = {
  slug: 'blog-ai',
  label: 'Blog AI',
  admin: {
    group: 'Blog',
    description:
      'Settings for AI-generated blog posts. Create a topic in Blog topics to queue an article; drafts are generated by the nightly job.',
  },
  access: {
    read: authenticated,
    update: authenticated,
  },
  fields: [
    {
      name: 'basePrompt',
      type: 'textarea',
      required: true,
      defaultValue: DEFAULT_BASE_PROMPT,
      admin: {
        rows: 24,
        description:
          'Base writing instructions sent to Claude for every generated post (brand voice, structure, SEO rules). Edits apply to the next generation run — no deploy needed.',
      },
    },
    {
      name: 'defaultAuthor',
      type: 'relationship',
      relationTo: 'authors',
      admin: { description: 'Author assigned to generated posts.' },
    },
    {
      name: 'notificationEmail',
      type: 'email',
      admin: {
        description: 'Receives "draft ready for review" and generation-failure emails. Leave empty to disable.',
      },
    },
  ],
}
