/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    authors: Author;
    'blog-topics': BlogTopic;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    faqs: Faq;
    leads: Lead;
    'newsletter-subscribers': NewsletterSubscriber;
    media: Media;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'blog-topics': BlogTopicsSelect<false> | BlogTopicsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('cs' | 'en') | ('cs' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'blog-ai': BlogAi;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'blog-ai': BlogAiSelect<false> | BlogAiSelect<true>;
  };
  locale: 'cs' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: {
      'generate-blog-post': WorkflowGenerateBlogPost;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment for this locale. Leave empty to generate from the title.
   */
  slug?: string | null;
  layout: (
    | HeroBlock
    | FeatureGridBlock
    | ContentBlock
    | MediaBlockType
    | StatsBlock
    | LogoCloudBlock
    | TestimonialBarBlock
    | IndustryCardsBlock
    | IndustrySectionBlock
    | ProcessStepsBlock
    | PricingTableBlock
    | PlanComparisonBlock
    | FAQAccordionBlock
    | SplitSectionBlock
    | CaseStudyGridBlock
    | BlogTeaserBlock
    | CTABannerBlock
    | ContactFormBlock
  )[];
  /**
   * Overrides for search engines and social sharing. Falls back to the document title/excerpt.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    image?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Chip label above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  text?: string | null;
  /**
   * First link renders as the filled CTA, second as outlined.
   */
  links?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Looping full-width video below the copy (takes precedence over image).
   */
  video?: (number | null) | Media;
  image?: (number | null) | Media;
  /**
   * Trust strip under the media (e.g. "Trusted in operations running …").
   */
  trust?: {
    label?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  variant?: ('centered' | 'split') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading?: string | null;
  text?: string | null;
  background?: ('light' | 'dark') | null;
  columns?: ('2' | '3' | '4') | null;
  features: {
    /**
     * Optional card media header.
     */
    image?: (number | null) | Media;
    imageStyle?: ('cover' | 'framed') | null;
    /**
     * Design-system glyph shown in a lime-tint square.
     */
    icon?:
      | (
          | 'IcoAIStyleColored'
          | 'IcoAIStyleDefault'
          | 'IcoAddLarge'
          | 'IcoAddSmall'
          | 'IcoAdjustments'
          | 'IcoAiPower'
          | 'IcoAnnotate'
          | 'IcoAnnotationReadyStyleDefault'
          | 'IcoAnnotationReadyStyleFlat'
          | 'IcoArrowDown'
          | 'IcoArrowLeft'
          | 'IcoArrowRight'
          | 'IcoArrowUp'
          | 'IcoBasket'
          | 'IcoBox'
          | 'IcoBulb'
          | 'IcoBulbAlt'
          | 'IcoCalendar'
          | 'IcoCamera'
          | 'IcoCardView'
          | 'IcoChart'
          | 'IcoChat'
          | 'IcoCheck'
          | 'IcoChevronDown'
          | 'IcoChevronLeft'
          | 'IcoChevronRight'
          | 'IcoClose'
          | 'IcoCog'
          | 'IcoConnector'
          | 'IcoController'
          | 'IcoCursor'
          | 'IcoDarkTheme'
          | 'IcoDashboard'
          | 'IcoDate'
          | 'IcoDelete'
          | 'IcoDesktop'
          | 'IcoDocumentation'
          | 'IcoDots'
          | 'IcoDownload'
          | 'IcoDropdownMenu'
          | 'IcoDuplicate'
          | 'IcoEdit'
          | 'IcoErrorStyleDefault'
          | 'IcoErrorStyleFlat'
          | 'IcoEthernet'
          | 'IcoExpand'
          | 'IcoEye'
          | 'IcoFilterTable'
          | 'IcoFocusTypeAuto'
          | 'IcoFocusTypeCapture'
          | 'IcoFocusTypeFixed'
          | 'IcoFullArrowDown'
          | 'IcoFullArrowRight'
          | 'IcoFullArrowUp'
          | 'IcoGSM'
          | 'IcoHamburger'
          | 'IcoHand'
          | 'IcoHome'
          | 'IcoHorizontal'
          | 'IcoImage'
          | 'IcoIndicator'
          | 'IcoInfere'
          | 'IcoInformation'
          | 'IcoInput'
          | 'IcoInvisible'
          | 'IcoLightTheme'
          | 'IcoLink'
          | 'IcoLocationArrow'
          | 'IcoLock'
          | 'IcoLogout'
          | 'IcoMail'
          | 'IcoMinus'
          | 'IcoModel'
          | 'IcoMotor'
          | 'IcoNoCamera'
          | 'IcoNote'
          | 'IcoOr'
          | 'IcoOutput'
          | 'IcoPause'
          | 'IcoPowerSource'
          | 'IcoRedo'
          | 'IcoRefresh'
          | 'IcoRemove'
          | 'IcoRemoveAnnotation'
          | 'IcoRotateLeft'
          | 'IcoRotateRight'
          | 'IcoRun'
          | 'IcoSave'
          | 'IcoSearch'
          | 'IcoSensor'
          | 'IcoSettings'
          | 'IcoShape'
          | 'IcoShare'
          | 'IcoSocialsSocialGithub'
          | 'IcoSocialsSocialLinkedin'
          | 'IcoSocialsSocialReddit'
          | 'IcoSocialsSocialXTwitter'
          | 'IcoSocialsSocialYoutube'
          | 'IcoSortBy'
          | 'IcoStopCapture'
          | 'IcoSuccessStyleDefault'
          | 'IcoSuccessStyleFlat'
          | 'IcoSupport'
          | 'IcoSwitch'
          | 'IcoTableView'
          | 'IcoTarget'
          | 'IcoTemperature'
          | 'IcoTerminal'
          | 'IcoTrash'
          | 'IcoUSB'
          | 'IcoUndo'
          | 'IcoUnlock'
          | 'IcoUpload'
          | 'IcoUser'
          | 'IcoVertical'
          | 'IcoVisible'
          | 'IcoXaxis'
          | 'IcoXor'
          | 'IcoYaxis'
          | 'IcoZoomIn'
          | 'IcoZoomOut'
        )
      | null;
    title: string;
    text?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('narrow' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType".
 */
export interface MediaBlockType {
  media: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  background?: ('light' | 'dark') | null;
  items: {
    /**
     * E.g. "3,600", "99.5%", "< 1 day".
     */
    value: string;
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  /**
   * E.g. "Trusted by manufacturing teams".
   */
  heading?: string | null;
  logos: {
    logo: number | Media;
    name: string;
    url?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBarBlock".
 */
export interface TestimonialBarBlock {
  /**
   * Chip label above the quote (e.g. "Customer story").
   */
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * A single testimonial renders as a large centered pull quote.
   */
  testimonials: (number | Testimonial)[];
  /**
   * Optional inline link after the attribution (e.g. "read the case study").
   */
  link?: {
    link?: {
      label?: string | null;
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialBar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  personName: string;
  personRole?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  companyLogo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustryCardsBlock".
 */
export interface IndustryCardsBlock {
  heading?: string | null;
  text?: string | null;
  cards: {
    image?: (number | null) | Media;
    title: string;
    text?: string | null;
    link?: {
      label?: string | null;
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
    };
    /**
     * Card link label, e.g. "Explore". Rendered with an arrow.
     */
    exploreLabel?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'industryCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustrySectionBlock".
 */
export interface IndustrySectionBlock {
  /**
   * Anchor id for deep links, e.g. "food" → /industries#food.
   */
  anchor?: string | null;
  /**
   * Chip label, e.g. "Food processing".
   */
  chip?: string | null;
  heading: string;
  text?: string | null;
  image?: (number | null) | Media;
  imageSide?: ('left' | 'right') | null;
  background?: ('white' | 'tinted') | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'industrySection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock".
 */
export interface ProcessStepsBlock {
  heading: string;
  text?: string | null;
  image?: (number | null) | Media;
  steps: {
    title: string;
    text?: string | null;
    id?: string | null;
  }[];
  cta?: {
    link?: {
      label?: string | null;
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
    };
  };
  /**
   * Stat strip at the bottom of the section.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTableBlock".
 */
export interface PricingTableBlock {
  heading?: string | null;
  text?: string | null;
  tiers: {
    name: string;
    /**
     * One-liner under the name, e.g. "Prove it on one camera before you scale."
     */
    tagline?: string | null;
    /**
     * E.g. "€390" / "9 900 Kč" or "Custom".
     */
    price: string;
    /**
     * E.g. "/ camera". Optional.
     */
    period?: string | null;
    /**
     * Billing note, e.g. "3-month minimum · hardware rental included".
     */
    subNote?: string | null;
    /**
     * Bold lead-in above features, e.g. "Everything in Standard and".
     */
    featuresLeadIn?: string | null;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
    };
    ctaVariant?: ('filled' | 'outlined') | null;
    /**
     * Renders as the dark "Most popular" card.
     */
    highlighted?: boolean | null;
    /**
     * Badge on the highlighted card, e.g. "Most popular".
     */
    badge?: string | null;
    id?: string | null;
  }[];
  /**
   * Small print below the table, e.g. VAT note.
   */
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlanComparisonBlock".
 */
export interface PlanComparisonBlock {
  heading?: string | null;
  /**
   * Tier names, in column order.
   */
  columns: {
    name: string;
    id?: string | null;
  }[];
  groups: {
    /**
     * Group header, e.g. "Inspection".
     */
    label: string;
    rows: {
      label: string;
      /**
       * One value per tier column: "✓", "—", or text like "5 / month".
       */
      values: {
        value?: string | null;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'planComparison';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock".
 */
export interface FAQAccordionBlock {
  heading?: string | null;
  faqs: (number | Faq)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitSectionBlock".
 */
export interface SplitSectionBlock {
  blog?: {
    /**
     * E.g. "From the blog".
     */
    heading?: string | null;
    limit?: number | null;
  };
  faq?: {
    /**
     * E.g. "Questions, answered."
     */
    heading?: string | null;
    faqs?: (number | Faq)[] | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'splitSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyGridBlock".
 */
export interface CaseStudyGridBlock {
  heading?: string | null;
  /**
   * Leave empty to show the latest case studies.
   */
  caseStudies?: (number | CaseStudy)[] | null;
  /**
   * Used when no case studies are selected manually.
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'caseStudyGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * URL segment for this locale. Leave empty to generate from the title.
   */
  slug?: string | null;
  customer: string;
  industry?: ('food' | 'pharma' | 'retail' | 'logistics') | null;
  /**
   * Featured study renders as the large two-column card on the listing.
   */
  featured?: boolean | null;
  customerLogo?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  /**
   * Short summary for listings and SEO fallback.
   */
  excerpt?: string | null;
  /**
   * Headline results, e.g. "99.7% – defect detection accuracy".
   */
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional long-form body — case studies are listing-only in v1.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Overrides for search engines and social sharing. Falls back to the document title/excerpt.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    image?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogTeaserBlock".
 */
export interface BlogTeaserBlock {
  heading?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock".
 */
export interface CTABannerBlock {
  heading: string;
  text?: string | null;
  /**
   * First link renders filled, second outlined.
   */
  links?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  /**
   * Form card title, e.g. "Book a demo".
   */
  heading?: string | null;
  /**
   * Small line beside the submit button.
   */
  microcopy?: string | null;
  /**
   * Show contact details and the map (from Site Settings) next to the form.
   */
  showSidebar?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * A post appears only in locales where it has a title and slug — leave a locale empty to keep the post out of that locale.
   */
  title: string;
  /**
   * URL segment for this locale. Leave empty to generate from the title.
   */
  slug?: string | null;
  /**
   * Short summary for listings, RSS and SEO fallback.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  heroStyle?: ('photo' | 'framed') | null;
  /**
   * Blockquotes render as lime callout boxes on the site.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Headline of the dark "Book a demo" section under the post, e.g. "Run the pipeline on your own products." Falls back to a default when empty.
   */
  ctaHeadline?: string | null;
  /**
   * Minutes — computed from content on save.
   */
  readingTime?: number | null;
  authors?: (number | Author)[] | null;
  categories?: (number | Category)[] | null;
  publishedAt?: string | null;
  /**
   * Overrides for search engines and social sharing. Falls back to the document title/excerpt.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Social sharing image (1200×630 recommended).
     */
    image?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * E.g. "CTO" or "Machine vision engineer".
   */
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL segment for this locale. Leave empty to generate from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Queue of article ideas for AI generation. Queued topics are picked up by the nightly job, which writes a bilingual draft post for review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-topics".
 */
export interface BlogTopic {
  id: number;
  /**
   * Working title / topic idea. Claude writes the final title itself.
   */
  title: string;
  /**
   * What the article should cover: angle, key points, facts to include, target reader. The more grounding, the better the draft.
   */
  description: string;
  /**
   * Optional one-off instructions for this article, on top of the Blog AI base prompt.
   */
  extraInstructions?: string | null;
  /**
   * Prefills publishedAt on the generated draft. Does not delay generation — topics generate on the next nightly run.
   */
  targetPublishDate?: string | null;
  /**
   * Set back to "Queued" to regenerate (overwrites the draft content; old text stays in version history).
   */
  status?: ('queued' | 'generating' | 'ready' | 'failed') | null;
  /**
   * The generated draft post.
   */
  post?: (number | null) | Post;
  /**
   * Last generation error, if any.
   */
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inquiries submitted through the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  phone?: string | null;
  message: string;
  industry?: ('food' | 'pharma' | 'retail' | 'logistics' | 'other') | null;
  /**
   * Pricing tier the visitor clicked before submitting, if any.
   */
  tier?: string | null;
  locale?: ('cs' | 'en') | null;
  /**
   * Path of the page the form was submitted from.
   */
  sourcePage?: string | null;
  status?: ('new' | 'contacted' | 'qualified' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog newsletter signups. No sending is wired up yet — export or connect later.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  locale?: ('cs' | 'en') | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editor-managed redirects, applied when a URL is not found.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path to redirect from, e.g. /en/old-page.
   */
  from: string;
  /**
   * Destination path or absolute URL.
   */
  to: string;
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'generate-blog-post' | null;
  taskSlug?: 'inline' | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'blog-topics';
        value: number | BlogTopic;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockTypeSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        testimonialBar?: T | TestimonialBarBlockSelect<T>;
        industryCards?: T | IndustryCardsBlockSelect<T>;
        industrySection?: T | IndustrySectionBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        pricingTable?: T | PricingTableBlockSelect<T>;
        planComparison?: T | PlanComparisonBlockSelect<T>;
        faqAccordion?: T | FAQAccordionBlockSelect<T>;
        splitSection?: T | SplitSectionBlockSelect<T>;
        caseStudyGrid?: T | CaseStudyGridBlockSelect<T>;
        blogTeaser?: T | BlogTeaserBlockSelect<T>;
        ctaBanner?: T | CTABannerBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  text?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  video?: T;
  image?: T;
  trust?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  background?: T;
  columns?: T;
  features?:
    | T
    | {
        image?: T;
        imageStyle?: T;
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType_select".
 */
export interface MediaBlockTypeSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  background?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        logo?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBarBlock_select".
 */
export interface TestimonialBarBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  testimonials?: T;
  link?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustryCardsBlock_select".
 */
export interface IndustryCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  cards?:
    | T
    | {
        image?: T;
        title?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        exploreLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustrySectionBlock_select".
 */
export interface IndustrySectionBlockSelect<T extends boolean = true> {
  anchor?: T;
  chip?: T;
  heading?: T;
  text?: T;
  image?: T;
  imageSide?: T;
  background?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock_select".
 */
export interface ProcessStepsBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  image?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTableBlock_select".
 */
export interface PricingTableBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  tiers?:
    | T
    | {
        name?: T;
        tagline?: T;
        price?: T;
        period?: T;
        subNote?: T;
        featuresLeadIn?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        ctaVariant?: T;
        highlighted?: T;
        badge?: T;
        id?: T;
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlanComparisonBlock_select".
 */
export interface PlanComparisonBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?:
    | T
    | {
        name?: T;
        id?: T;
      };
  groups?:
    | T
    | {
        label?: T;
        rows?:
          | T
          | {
              label?: T;
              values?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock_select".
 */
export interface FAQAccordionBlockSelect<T extends boolean = true> {
  heading?: T;
  faqs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitSectionBlock_select".
 */
export interface SplitSectionBlockSelect<T extends boolean = true> {
  blog?:
    | T
    | {
        heading?: T;
        limit?: T;
      };
  faq?:
    | T
    | {
        heading?: T;
        faqs?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyGridBlock_select".
 */
export interface CaseStudyGridBlockSelect<T extends boolean = true> {
  heading?: T;
  caseStudies?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogTeaserBlock_select".
 */
export interface BlogTeaserBlockSelect<T extends boolean = true> {
  heading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock_select".
 */
export interface CTABannerBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  heading?: T;
  microcopy?: T;
  showSidebar?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  heroStyle?: T;
  content?: T;
  ctaHeadline?: T;
  readingTime?: T;
  authors?: T;
  categories?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-topics_select".
 */
export interface BlogTopicsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  extraInstructions?: T;
  targetPublishDate?: T;
  status?: T;
  post?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  customer?: T;
  industry?: T;
  featured?: T;
  customerLogo?: T;
  heroImage?: T;
  excerpt?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  personName?: T;
  personRole?: T;
  company?: T;
  avatar?: T;
  companyLogo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  message?: T;
  industry?: T;
  tier?: T;
  locale?: T;
  sourcePage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Plain text link before the CTA (e.g. "App login").
   */
  secondaryLink?: {
    link?: {
      label?: string | null;
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
    };
  };
  /**
   * Highlighted button at the end of the navigation.
   */
  cta?: {
    link?: {
      label?: string | null;
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      newTab?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                label: string;
                type?: ('internal' | 'external') | null;
                page?: (number | null) | Page;
                url?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short company blurb shown next to the logo.
   */
  note?: string | null;
  /**
   * Links in the bottom bar (e.g. Privacy Policy).
   */
  legalLinks?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Legal entity for the © line, e.g. "Robopipe s.r.o." (year is added automatically).
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Sales inbox that receives new lead notifications.
   */
  leadNotificationEmail?: string | null;
  /**
   * Public contact email shown on the site.
   */
  contactEmail?: string | null;
  /**
   * Details shown on the contact page next to the form.
   */
  contact?: {
    /**
     * Displayed phone number, e.g. "+420 728 488 116".
     */
    phone?: string | null;
    /**
     * E.g. "Mon–Fri, 8:00–17:00 CET".
     */
    phoneHours?: string | null;
    /**
     * Postal address, one line per row.
     */
    address?: string | null;
    /**
     * Static map screenshot of the HQ.
     */
    mapImage?: (number | null) | Media;
  };
  socials?:
    | {
        platform: 'linkedin' | 'github' | 'youtube' | 'x' | 'facebook' | 'instagram';
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    /**
     * Default meta title, also used as suffix: "Page — Robopipe".
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Settings for AI-generated blog posts. Create a topic in Blog topics to queue an article; drafts are generated by the nightly job.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-ai".
 */
export interface BlogAi {
  id: number;
  /**
   * Base writing instructions sent to Claude for every generated post (brand voice, structure, SEO rules). Edits apply to the next generation run — no deploy needed.
   */
  basePrompt: string;
  /**
   * Author assigned to generated posts.
   */
  defaultAuthor?: (number | null) | Author;
  /**
   * Receives "draft ready for review" and generation-failure emails. Leave empty to disable.
   */
  notificationEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  secondaryLink?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
      };
  cta?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  note?: T;
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  leadNotificationEmail?: T;
  contactEmail?: T;
  contact?:
    | T
    | {
        phone?: T;
        phoneHours?: T;
        address?: T;
        mapImage?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-ai_select".
 */
export interface BlogAiSelect<T extends boolean = true> {
  basePrompt?: T;
  defaultAuthor?: T;
  notificationEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowGenerate-blog-post".
 */
export interface WorkflowGenerateBlogPost {
  input: {
    topicId: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}